//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseWebsite : DbContext
    {
        public DatabaseWebsite()
            : base("name=DatabaseWebsite")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mensagens> mensagens { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<treinos> treinos { get; set; }
        public virtual DbSet<user_alimentacao> user_alimentacao { get; set; }
        public virtual DbSet<user_clinica> user_clinica { get; set; }
        public virtual DbSet<user_fotos> user_fotos { get; set; }
        public virtual DbSet<user_medicoes> user_medicoes { get; set; }
        public virtual DbSet<user_peso> user_peso { get; set; }
        public virtual DbSet<user_plano> user_plano { get; set; }
        public virtual DbSet<user_treino> user_treino { get; set; }
    }
}
