//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensagens
    {
        public int id { get; set; }
        public string texto { get; set; }
        public string userVisto { get; set; }
        public string trainerVisto { get; set; }
        public int perfil_id { get; set; }
    
        public virtual perfil perfil { get; set; }
    }
}
