//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> dataInscricao { get; set; }
        public string nomeCompleto { get; set; }
        public string nomePerfil { get; set; }
        public Nullable<int> contacto { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public Nullable<int> NIF { get; set; }
        public string rua { get; set; }
        public string localidade { get; set; }
        public string cidade { get; set; }
        public string codigoPostal { get; set; }
        public string foto { get; set; }
        public string respondido { get; set; }
    }
}
