//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_medicoes
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<decimal> braco { get; set; }
        public Nullable<decimal> abdominal { get; set; }
        public Nullable<decimal> peitoral { get; set; }
        public Nullable<decimal> coxa { get; set; }
        public Nullable<decimal> gemeo { get; set; }
    }
}
