//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_alimentacao
    {
        public int id { get; set; }
        public Nullable<int> refeicoesDiarias { get; set; }
        public string acordar { get; set; }
        public string localAcordar { get; set; }
        public string pequeno { get; set; }
        public string localPequeno { get; set; }
        public string manha { get; set; }
        public string localManha { get; set; }
        public string almoco { get; set; }
        public string localAlmoco { get; set; }
        public string tarde { get; set; }
        public string localTarde { get; set; }
        public string jantar { get; set; }
        public string localJantar { get; set; }
        public string ceia { get; set; }
        public string localCeia { get; set; }
        public string alergias { get; set; }
        public string info { get; set; }
        public string respondido { get; set; }
        public int perfil_id { get; set; }
    
        public virtual perfil perfil { get; set; }
    }
}
