//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_fotos
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string frontal { get; set; }
        public string lateral { get; set; }
        public string traseira { get; set; }
    }
}
