//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Fitness_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_clinica
    {
        public int id { get; set; }
        public Nullable<int> altura { get; set; }
        public string sexo { get; set; }
        public string diabetes { get; set; }
        public string colesterol { get; set; }
        public string renais { get; set; }
        public string transplantes { get; set; }
        public string textoTransplantes { get; set; }
        public string cardiacos { get; set; }
        public string textoCardiacos { get; set; }
        public string articulares { get; set; }
        public string textoArticulares { get; set; }
        public string outros { get; set; }
        public string medicacao { get; set; }
        public string textoMedicacao { get; set; }
        public string respondido { get; set; }
        public int perfil_id { get; set; }
    
        public virtual perfil perfil { get; set; }
    }
}
